# Generated by Django 2.2.5 on 2019-10-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
